### ISSUE TITLE
[HTTP] Post... failed, error: connection failed sur ESP8266

### ISSUE THREAD

**Issue by felix-lecluse** [maditnerd/discord_test#3]
Bonjour, j'ai toujours cette erreur [HTTP] Post... failed, error: connection failed
Je suis sur ESP8266.
J'ai bien mis mon ssid, mot de passe wpa2, webhook et tts et j'ai essayer de changer le fingerprint parce que j'ai discord.com à la place de discordapp.com donc j'ai mis ceci
`const uint8_t discordappFingerprint[20] = {0xFD, 0x48, 0x0C, 0xD1, 0x70, 0x41, 0x1F, 0x28, 0x97, 0x32, 0x62, 0x49, 0xB3, 0x5B, 0x53, 0x5A, 0xF9, 0x61, 0x9C, 0xB4};`

Je ne suis pas très expérimenté donc je vous donne ce que me donne le monitor : 
⸮Hl⸮⸮⸮lE⸮4C(&⸮[WiFi] Connecting to: freebox_VPCJJY
......................
[WiFi] Connected
[HTTP] Connecting to Discord...
[HTTP] Message: Bonjour
[HTTP] TTS: false
[HTTP] Post... failed, error: connection failed

et les logs : 
Executable segment sizes:

IROM   : 363952          - code in flash         (default or ICACHE_FLASH_ATTR) 

IRAM   : 26892   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 

DATA   : 1252  )         - initialized variables (global, static) in RAM/HEAP 

RODATA : 1644  ) / 81920 - constants             (global, static) in RAM/HEAP 

BSS    : 25048 )         - zeroed variables      (global, static) in RAM/HEAP 

Le croquis utilise 393740 octets (41%) de l'espace de stockage de programmes. Le maximum est de 958448 octets.
Les variables globales utilisent 27944 octets (34%) de mémoire dynamique, ce qui laisse 53976 octets pour les variables locales. Le maximum est de 81920 octets.
esptool.py v2.8
Serial port COM4
Connecting....
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: bc:dd:c2:24:9c:70
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 1MB
Compressed 397888 bytes to 293123...

Writing at 0x00000000... (5 %)
Writing at 0x00004000... (11 %)
Writing at 0x00008000... (16 %)
Writing at 0x0000c000... (22 %)
Writing at 0x00010000... (27 %)
Writing at 0x00014000... (33 %)
Writing at 0x00018000... (38 %)
Writing at 0x0001c000... (44 %)
Writing at 0x00020000... (50 %)
Writing at 0x00024000... (55 %)
Writing at 0x00028000... (61 %)
Writing at 0x0002c000... (66 %)
Writing at 0x00030000... (72 %)
Writing at 0x00034000... (77 %)
Writing at 0x00038000... (83 %)
Writing at 0x0003c000... (88 %)
Writing at 0x00040000... (94 %)
Writing at 0x00044000... (100 %)
Wrote 397888 bytes (293123 compressed) at 0x00000000 in 29.9 seconds (effective 106.4 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

J'ai même essayer avec discordapp.com et le fingerprint d'avant mais ça ne fonctionne pas non plus.
Sur Arduino IDE 1.8.10 j'ai pris les cartes esp8266 version 2.7.4

**Comment by remisarrailh** [comment]
Il y a des changements au niveau des bots discord, du coup ça marche peut être plus, je vais tester ça.

**Comment by remisarrailh** [comment]
Ça ne marchait plus de mon coté, même erreur.
J'ai mis à jour le code, ça devrait marcher.

Vu que j'ai un peu la flemme de mettre à jour le certificat, j'ai viré la vérification du certificat.
Niveau sécurité c'est moins bien car il ne vérifie pas que discord.com est vraiment discord.com.
Mais ça devrait pas causer de problèmes et simplifier un peu les choses.

**Comment by felix-lecluse** [comment]
> 
> 
> Ça ne marchait plus de mon coté, même erreur.
> J'ai mis à jour le code, ça devrait marcher.
> 
> Vu que j'ai un peu la flemme de mettre à jour le certificat, j'ai viré la vérification du certificat.
> Niveau sécurité c'est moins bien car il ne vérifie pas que discord.com est vraiment discord.com.
> Mais ça devrait pas causer de problèmes et simplifier un peu les choses.

Merci beaucoup, je ne m'attendais pas à une réponse aussi rapide.
